[tools]
lefthook = "1.10.10"
node = "23.6.1"
"npm:markdownlint-cli2" = "0.17.2"

[hooks]
enter = "lefthook install"

[[watch_files]]
patterns = ["lefthook.yml"]
run = "lefthook install"

[[watch_files]]
patterns = ["mise.toml", "**/mise.toml"]
run = "mise install"

[[watch_files]]
patterns = [
	"*.psd",
	"*.xdf",
	"*.kra",
	"*.png",
	"*.jpg",
	"*.jpeg",
	"*.tiff",
	"*.tga",
	"*.aup3",
	"*.sesx",
	"*.flp",
	"*.rpp",
	"*.als",
	"*.wav",
	"*.ogg",
	"*.mp3",
	"*.aif",
	"*.aiff",
	"*.mid",
	"*.midi",
]
run = "mise lfs:checkout"

[task_config]
includes = ["raw_art/tasks.toml", ".mise/tasks"]

[tasks."pre-commit"]
hide = true
description = "Run pre-commit tasks"
# depends = ["pre-commit:*"]

[tasks."lint:all"]
description = "Run linters"
run = "markdownlint-cli2"

[tasks."lint:diff"]
description = "Run linters on diff"
run = "markdownlint-cli2 "

[tasks."diff:files"]
description = "Get files that have changed since the last commit on origin/main"
run = "git diff --name-only --diff-filter=d origin/main"
